name: fastq_bench
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - alsa-lib=1.2.15.2
  - binutils_impl_linux-64=2.45
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - cairo=1.18.0
  - curl=8.18.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - fribidi=1.0.16
  - gcc_impl_linux-64=15.2.0
  - gfortran_impl_linux-64=15.2.0
  - giflib=5.2.2
  - graphite2=1.3.14
  - gsl=2.7
  - gxx_impl_linux-64=15.2.0
  - gzip=1.14
  - harfbuzz=12.3.0
  - htslib=1.23
  - icu=73.2
  - kernel-headers_linux-64=5.14.0
  - keyutils=1.6.3
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libblas=3.11.0
  - libcblas=3.11.0
  - libcups=2.3.3
  - libcurl=8.18.0
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-devel_linux-64=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.84.1
  - libgomp=15.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.67.0
  - libopenblas=0.3.30
  - libpng=1.6.53
  - libsanitizer=15.2.0
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.0
  - libuuid=2.41.3
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.9.9
  - libzlib=1.3.1
  - make=4.4.1
  - ncbi-ngs-sdk=2.9.0
  - ncurses=6.5
  - openjdk=25.0.1
  - openssl=3.6.0
  - pango=1.54.0
  - pcre2=10.44
  - perl=5.26.2
  - perl-app-cpanminus=1.7044
  - perl-business-isbn=3.004
  - perl-business-isbn-data=20140910.003
  - perl-carp=1.38
  - perl-constant=1.33
  - perl-data-dumper=2.173
  - perl-encode=2.88
  - perl-exporter=5.72
  - perl-extutils-makemaker=7.36
  - perl-file-path=2.16
  - perl-file-temp=0.2304
  - perl-mime-base64=3.15
  - perl-parent=0.236
  - perl-uri=1.76
  - perl-xml-libxml=2.0132
  - perl-xml-namespacesupport=1.12
  - perl-xml-sax=1.02
  - perl-xml-sax-base=1.09
  - perl-xsloader=0.24
  - picard=3.4.0
  - pigz=2.8
  - pixman=0.46.4
  - pthread-stubs=0.4
  - r-base=4.3.3
  - readline=8.3
  - renano=1.3
  - samtools=1.23
  - sed=4.9
  - spring=1.1.1
  - sra-tools=2.10.0
  - sysroot_linux-64=2.34
  - time=1.9
  - tk=8.6.13
  - tktable=2.10
  - tzdata=2025c
  - unzip=6.0
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xorg-libxtst=1.2.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zip=3.0
  - zlib=1.3.1
  - zstd=1.5.7
